# fly.toml app configuration file generated for supabase-flask-demo on 2023-09-21T14:52:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "supabase-flask-demo"
primary_region = "cdg"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
