name: Deploy Migrations/Edge Functions to Staging

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ vars.STAGING_PROJECT_ID }}
      GITHUB_CLIENT_ID: "9e44"
      GITHUB_SECRET: "2cc178e"

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      
      - name: Database Migrations push
        run: supabase db push

      - name: Edge Functions deployment
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
